# Generated by Django 6.0.5 on 2026-05-31 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RewardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('vendor', models.CharField(max_length=200)),
                ('points_cost', models.IntegerField()),
                ('stock_status', models.CharField(default='Available', max_length=100)),
                ('icon_class', models.CharField(default='fa-utensils', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SkillTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('tech', 'Tech'), ('business', 'Business'), ('career', 'Career')], max_length=20)),
                ('description', models.TextField()),
                ('points_awarded', models.IntegerField(default=100)),
                ('difficulty', models.CharField(max_length=50)),
            ],
        ),
    ]
