# Generated by Django 6.0.5 on 2026-06-02 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_task_taskcompletion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.skilltrack'),
        ),
    ]
