# Generated by Django 6.0.5 on 2026-06-05 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_task_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='ai_chat_history',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('DIAGNOSTIC', 'Taking AI Assessment'), ('ACTIVE', 'Active Learning Tasks'), ('COMPLETED', 'Track Fully Concluded')], default='DIAGNOSTIC', max_length=20),
        ),
    ]
