# Generated by Django 6.0.5 on 2026-06-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_enrollment_ai_chat_history_alter_enrollment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcompletion',
            name='ai_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskcompletion',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Under AI Review'), ('FAILED', 'Needs Revision (Try Again)'), ('PASSED', 'Passed (100% Competency)')], default='PENDING', max_length=15),
        ),
        migrations.AddField(
            model_name='taskcompletion',
            name='submission_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskcompletion',
            name='date_completed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
