# Generated by Django 6.0.5 on 2026-06-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_taskcompletion_ai_feedback_taskcompletion_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='learning_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
