# Generated by Django 6.0.5 on 2026-06-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_task_learning_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskcompletion',
            old_name='ai_feedback',
            new_name='admin_feedback',
        ),
        migrations.AddField(
            model_name='task',
            name='assignment_type',
            field=models.CharField(choices=[('text', 'Manual Text Submission'), ('multiple_choice', 'Multiple Choice (Single Option)'), ('checkbox', 'Checkbox Selection (Multiple Options)')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='concept_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='correct_options',
            field=models.JSONField(blank=True, default=list, help_text='Exact matching text choices that equal success.'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='local_example',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='options',
            field=models.JSONField(blank=True, default=list, help_text='List of choices for quizzes. Leave empty for text.'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(help_text='Holds the practical assignment/assessment prompt question.'),
        ),
        migrations.AlterField(
            model_name='taskcompletion',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Under Admin Review'), ('FAILED', 'Needs Revision (Try Again)'), ('PASSED', 'Passed (100% Competency)')], default='PENDING', max_length=15),
        ),
    ]
